/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BoundaryRouteImport } from './routes/boundary'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as RefusalRouteImport } from './routes/refusal'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ZkRouteImport } from './routes/zk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BoundaryRoute = BoundaryRouteImport.update({
  id: '/boundary',
  path: '/boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const RefusalRoute = RefusalRouteImport.update({
  id: '/refusal',
  path: '/refusal',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ZkRoute = ZkRouteImport.update({
  id: '/zk',
  path: '/zk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/boundary': typeof BoundaryRoute
  '/demo': typeof DemoRoute
  '/pilot': typeof PilotRoute
  '/refusal': typeof RefusalRoute
  '/verify': typeof VerifyRoute
  '/zk': typeof ZkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/boundary': typeof BoundaryRoute
  '/demo': typeof DemoRoute
  '/pilot': typeof PilotRoute
  '/refusal': typeof RefusalRoute
  '/verify': typeof VerifyRoute
  '/zk': typeof ZkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/boundary': typeof BoundaryRoute
  '/demo': typeof DemoRoute
  '/pilot': typeof PilotRoute
  '/refusal': typeof RefusalRoute
  '/verify': typeof VerifyRoute
  '/zk': typeof ZkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/boundary'
    | '/demo'
    | '/pilot'
    | '/refusal'
    | '/verify'
    | '/zk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/boundary'
    | '/demo'
    | '/pilot'
    | '/refusal'
    | '/verify'
    | '/zk'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/boundary'
    | '/demo'
    | '/pilot'
    | '/refusal'
    | '/verify'
    | '/zk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BoundaryRoute: typeof BoundaryRoute
  DemoRoute: typeof DemoRoute
  PilotRoute: typeof PilotRoute
  RefusalRoute: typeof RefusalRoute
  VerifyRoute: typeof VerifyRoute
  ZkRoute: typeof ZkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boundary': {
      id: '/boundary'
      path: '/boundary'
      fullPath: '/boundary'
      preLoaderRoute: typeof BoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refusal': {
      id: '/refusal'
      path: '/refusal'
      fullPath: '/refusal'
      preLoaderRoute: typeof RefusalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zk': {
      id: '/zk'
      path: '/zk'
      fullPath: '/zk'
      preLoaderRoute: typeof ZkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BoundaryRoute: BoundaryRoute,
  DemoRoute: DemoRoute,
  PilotRoute: PilotRoute,
  RefusalRoute: RefusalRoute,
  VerifyRoute: VerifyRoute,
  ZkRoute: ZkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
